#!/usr/bin/env python3
"""
render_fleet_report.py

Joins fleet-versions.csv (from fleet_sbom_scan.py) with
fleet-vulns-summary.csv (from fleet_vuln_scan.py) into ONE self-contained
HTML file: no external CSS/JS, no CDN calls, so it survives being handed
to a Confluence-publish step as-is. This is answering "does Syft have a
built-in report format" -- neither Syft nor Grype ship an HTML output,
and their own Go-template option can only render ITS OWN tool's data
(Syft templates see packages, Grype templates see CVEs) -- not both
merged into one row per image, which is what a fleet dashboard needs.
Hence this small renderer.

Usage:
  ./render_fleet_report.py fleet-versions.csv fleet-vulns-summary.csv fleet-report.html
"""
import csv
import html
import sys

SEVERITY_COLORS = {
    "critical": ("#FCEBEB", "#791F1F"),  # bg, text -- c-red 50/800
    "high": ("#FAEEDA", "#633806"),      # c-amber 50/800
    "medium": ("#FAEEDA", "#854F0B"),    # c-amber 50/600
    "low": ("#F1EFE8", "#444441"),       # c-gray 50/800
    "negligible": ("#F1EFE8", "#5F5E5A"),
}


def load_csv(path):
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def badge(count, severity):
    count = str(count)
    if count in ("n/a", "scan-failed") or count == "0":
        bg, fg = "#F1EFE8", "#5F5E5A"
    else:
        bg, fg = SEVERITY_COLORS.get(severity, ("#F1EFE8", "#444441"))
    return f'<span style="background:{bg};color:{fg};padding:2px 8px;border-radius:10px;font-size:12px;font-weight:500;">{html.escape(count)}</span>'


def render(versions_rows, vulns_rows, package_columns):
    vulns_by_key = {(r["repository"], r["tag"]): r for r in vulns_rows}

    body_rows = []
    for v in versions_rows:
        key = (v["repository"], v["tag"])
        vu = vulns_by_key.get(key, {})

        version_cells = "".join(
            f'<td>{html.escape(v.get(col, "not found"))}</td>' for col in package_columns
        )

        sev_cells = "".join(
            f"<td>{badge(vu.get(f'{sev}_count', 'n/a'), sev)}</td>"
            for sev in ["critical", "high", "medium", "low", "negligible"]
        )

        cve_ids = [c for c in vu.get("cve_ids", "").split(";") if c]
        detail = ""
        if cve_ids:
            items = "".join(f"<li><code>{html.escape(c)}</code></li>" for c in cve_ids)
            detail = (
                f'<details><summary>{len(cve_ids)} CVE'
                f'{"s" if len(cve_ids) != 1 else ""}</summary>'
                f'<ul style="margin:6px 0 0;padding-left:18px;">{items}</ul></details>'
            )

        body_rows.append(
            "<tr>"
            f'<td><code>{html.escape(v["repository"])}</code></td>'
            f'<td>{html.escape(v["tag"])}</td>'
            f"{version_cells}"
            f"{sev_cells}"
            f'<td>{detail}</td>'
            "</tr>"
        )

    package_headers = "".join(f"<th>{html.escape(col.replace('_version', ''))}</th>" for col in package_columns)

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, Helvetica, Arial, sans-serif; color: #2C2C2A; margin: 0; padding: 16px; }}
  h1 {{ font-size: 18px; font-weight: 500; margin: 0 0 4px; }}
  p.sub {{ color: #5F5E5A; font-size: 13px; margin: 0 0 16px; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 13px; }}
  th, td {{ text-align: left; padding: 6px 10px; border-bottom: 1px solid #D3D1C7; white-space: nowrap; }}
  th {{ background: #F1EFE8; font-weight: 500; }}
  code {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; }}
  details summary {{ cursor: pointer; font-size: 12px; color: #185FA5; }}
  ul {{ font-size: 12px; }}
</style>
</head>
<body>
<h1>Fleet image report</h1>
<p class="sub">Versions from Syft SBOMs, vulnerability counts from Grype. Generated by the CI pipeline.</p>
<table>
<thead><tr>
  <th>Repository</th><th>Tag</th>{package_headers}
  <th>Critical</th><th>High</th><th>Medium</th><th>Low</th><th>Negligible</th>
  <th>CVE detail</th>
</tr></thead>
<tbody>
{''.join(body_rows)}
</tbody>
</table>
</body>
</html>"""


def main():
    if len(sys.argv) != 4:
        sys.exit(f"Usage: {sys.argv[0]} <fleet-versions.csv> <fleet-vulns-summary.csv> <out.html>")
    versions_csv, vulns_csv, out_html = sys.argv[1:4]

    versions_rows = load_csv(versions_csv)
    vulns_rows = load_csv(vulns_csv)

    package_columns = [
        c for c in (versions_rows[0].keys() if versions_rows else [])
        if c.endswith("_version")
    ]

    html_out = render(versions_rows, vulns_rows, package_columns)
    with open(out_html, "w") as f:
        f.write(html_out)

    print(f"Wrote {out_html} ({len(versions_rows)} images)")


if __name__ == "__main__":
    main()
