#!/usr/bin/env python3
"""
repo_scan.py — Scan, scrub, and chunk a repo for safe AI chat upload.
======================================================================

USAGE:
  python repo_scan.py <repo_folder> <tag>

EXAMPLES:
  python repo_scan.py /path/to/myrepo          myproject
  python repo_scan.py .                         current_repo
  python repo_scan.py ~/work/api-service        api_service_v2

ARGUMENTS:
  repo_folder   Path to the repo you want to scan and flatten.
  tag           Short name used to label all output files.
                Use underscores, no spaces.  e.g.  my_project

OPTIONS (all have defaults — only use when you need to override):
  --output      Output directory           default: ./repo_scans/<tag>
  --limit       Max chars per chunk        default: 90000
  --rules       security_rules.yaml path  default: ./security_rules.yaml
  --mode        redact (default) — tokenise + write clean file + report
                report              — scan and report only, no file changes
  --no-split    Stop after scrub, do not produce chunk files
  --max-file-kb Skip source files larger than this many KB  default: 500

WHAT IT PRODUCES:
  repo_scans/<tag>/
    <tag>_flat.txt          Raw flattened repo  (pre-scrub)
    <tag>_clean.txt         Tokenised clean file
    <tag>_report.txt        Full security report  (READ THIS)
    <tag>_map.json          Token ↔ original map  ⚠ NEVER UPLOAD
    chunks/
      <tag>_chunk_01_of_N.txt   ← upload these to your gov chatbot
      <tag>_chunk_02_of_N.txt
      ...

TO REVERT TOKENS IN BOT RESPONSES:
  python security_revert.py --response-file bot_answer.txt --tag <tag>
  python security_revert.py --response "bot said [SSN-0001]…" --tag <tag>

DEPENDENCIES:
  pip install pyyaml pathspec detect-secrets
"""

import argparse
import sys
from pathlib import Path

# ── guard: must be able to find _scanner package ─────────────────────────────
try:
    from _scanner.warnings import print_startup, print_stage, print_completion
    from _scanner import flattener, scrubber, splitter
except ImportError as e:
    print(f"\n[ERROR] Cannot import _scanner package: {e}")
    print("  Make sure repo_scan.py is in the same folder as the _scanner/ directory.")
    sys.exit(1)

DEFAULTS = {
    "output_base": "./repo_scans",
    "limit":       90_000,
    "rules":       "./security_rules.yaml",
    "mode":        "redact",
    "max_file_kb": 500,
}


def parse_args():
    p = argparse.ArgumentParser(
        prog="repo_scan.py",
        description="Scan, scrub, and chunk a repo for safe AI chat upload.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python repo_scan.py /path/to/myrepo  myproject\n"
            "  python repo_scan.py .                current_repo\n"
            "  python repo_scan.py ~/work/api       api_v2  --limit 85000\n"
        ),
    )
    p.add_argument("repo",  metavar="repo_folder",
                   help="Path to the repo to scan")
    p.add_argument("tag",   metavar="tag",
                   help="Short label for output files  (use_underscores)")
    p.add_argument("--output",      default=None,
                   help=f"Output directory  (default: {DEFAULTS['output_base']}/<tag>)")
    p.add_argument("--limit",       default=DEFAULTS["limit"],      type=int,
                   help=f"Max characters per chunk  (default: {DEFAULTS['limit']:,})")
    p.add_argument("--rules",       default=DEFAULTS["rules"],
                   help=f"security_rules.yaml path  (default: {DEFAULTS['rules']})")
    p.add_argument("--mode",        default=DEFAULTS["mode"],
                   choices=["redact", "report"],
                   help="redact = tokenise + report (default) | report = dry-run only")
    p.add_argument("--no-split",    action="store_true",
                   help="Stop after scrub, skip chunk splitting")
    p.add_argument("--max-file-kb", default=DEFAULTS["max_file_kb"], type=int,
                   help=f"Skip source files larger than N KB  (default: {DEFAULTS['max_file_kb']})")
    p.add_argument("--include-gitignored", action="store_true",
                   help="Include files normally excluded by .gitignore (use with caution)")
    return p.parse_args()


def _gitignore_for_output(out_dir: Path, tag: str):
    """Write a .gitignore that protects the map file and raw flat."""
    content = f"""# Generated by repo_scan.py
# These files contain sensitive data — never commit or share them.

# Substitution map — contains ALL original sensitive values
{tag}_map.json

# Raw unscanned flat file
{tag}_flat.txt

# All scan outputs for this tag (comment out to allow committing chunks)
{tag}_*

# Chunk files (contain tokenised but still potentially sensitive code)
chunks/

# Security reports
{tag}_report.txt
{tag}_report.json
"""
    gi_path = out_dir / ".gitignore"
    gi_path.write_text(content, encoding="utf-8")
    return gi_path


def main():
    args    = parse_args()
    repo    = Path(args.repo).resolve()
    tag     = args.tag.replace(" ", "_")
    out_dir = Path(args.output) if args.output else Path(DEFAULTS["output_base"]) / tag
    rules_p = Path(args.rules)

    # ── paths ─────────────────────────────────────────────────────────────────
    flat_p   = out_dir / f"{tag}_flat.txt"
    clean_p  = out_dir / f"{tag}_clean.txt"
    report_p = out_dir / f"{tag}_report.txt"
    map_p    = out_dir / f"{tag}_map.json"
    chunks_d = out_dir / "chunks"

    # ── startup ───────────────────────────────────────────────────────────────
    print_startup()

    print(f"  Repo    : {repo}")
    print(f"  Tag     : {tag}")
    print(f"  Output  : {out_dir}")
    print(f"  Limit   : {args.limit:,} chars/chunk")
    print(f"  Mode    : {args.mode}")
    print(f"  Rules   : {rules_p}")

    if not repo.exists():
        print(f"\n[ERROR] Repo folder not found: {repo}")
        sys.exit(1)
    if not rules_p.exists():
        print(f"\n[ERROR] Rules file not found: {rules_p}")
        print("  Make sure security_rules.yaml is in the same folder as repo_scan.py.")
        sys.exit(1)

    out_dir.mkdir(parents=True, exist_ok=True)

    # ── .gitignore ────────────────────────────────────────────────────────────
    gi = _gitignore_for_output(out_dir, tag)
    print(f"\n  ✓ .gitignore written → {gi}")

    # ── Stage 1: Flatten ──────────────────────────────────────────────────────
    print_stage("STAGE 1 — FLATTEN")
    stats = flattener.run(
        root                = repo,
        out_path            = flat_p,
        max_file_kb         = args.max_file_kb,
        include_gitignored  = args.include_gitignored,
    )
    print(f"  Files included : {stats['included']}")
    print(f"  Files skipped  : {stats['skipped']}")
    print(f"  .gitignore     : {'loaded ✓' if stats['spec_loaded'] else 'not found'}")
    if stats.get("gitignore_skipped"):
        print(f"  ⚠  {len(stats['gitignore_skipped'])} file(s) skipped by .gitignore — NOT scanned:")
        for f in stats["gitignore_skipped"]:
            print(f"       {f}")
        print(f"     Use --include-gitignored to scan these too.")
    print(f"  ✓ Flat file    → {flat_p.name}")

    # ── Stage 2: Scrub ────────────────────────────────────────────────────────
    print_stage("STAGE 2 — SECURITY SCAN")
    result = scrubber.run(
        in_path     = flat_p,
        out_path    = clean_p,
        report_path = report_p,
        map_path    = map_p,
        rules_path  = rules_p,
        tag         = tag,
        mode        = args.mode,
    )
    print(f"  Rules loaded   : {result['rules_loaded']}")
    print(f"  Auto-tokenised : {result['auto']}")
    print(f"  Manual review  : {result['suggest']}")
    print(f"  Unique tokens  : {result['unique_tokens']}")
    if args.mode == "redact":
        print(f"  ✓ Clean file   → {clean_p.name}")
        print(f"  ✓ Map          → {map_p.name}  ⚠ KEEP THIS SECURE")
    print(f"  ✓ Report       → {report_p.name}")

    if result["suggest"] > 0:
        print(f"\n  ⚠  {result['suggest']} item(s) need manual review — check section 5 of the report.")

    # ── Stage 3: Split ────────────────────────────────────────────────────────
    if args.no_split or args.mode == "report":
        if args.no_split:
            print("\n  [SPLIT] Skipped (--no-split).")
        else:
            print("\n  [SPLIT] Skipped (report mode — no clean file produced).")
    else:
        print_stage("STAGE 3 — SPLIT")
        split_result = splitter.run(
            in_path = clean_p,
            out_dir = chunks_d,
            tag     = tag,
            limit   = args.limit,
        )
        n = split_result["chunks"]
        print(f"  Chunks produced: {n}")
        for fname in split_result["files"]:
            print(f"    → {fname}")

    # ── done ──────────────────────────────────────────────────────────────────
    print(f"\n{'='*60}")
    print(f"  SCAN COMPLETE — {tag}")
    print(f"{'='*60}")
    print(f"  Output folder  : {out_dir}")
    if args.mode == "redact" and not args.no_split:
        print(f"\n  UPLOAD THESE TO YOUR GOV CHATBOT:")
        if "split_result" in dir():
            for fname in split_result["files"]:
                print(f"    {chunks_d / fname}")
        print(f"\n  NEVER UPLOAD:")
        print(f"    {map_p}")
        print(f"\n  TO REVERT BOT RESPONSES:")
        print(f"    python security_revert.py --response-file bot_answer.txt --tag {tag}")
    print(f"{'='*60}")

    print_completion()


if __name__ == "__main__":
    main()
